<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'DR',
  'author' => 'Max Santolo',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Dashboard_reception',
  'published_date' => '2018-10-31 12:06:36',
  'type' => 'module',
  'version' => 1540987596,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Dashboard_reception',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'DR_Eventi',
      'class' => 'DR_Eventi',
      'path' => 'modules/DR_Eventi/DR_Eventi.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/dr_eventi_leads_Leads.php',
      'to_module' => 'Leads',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/dr_eventi_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_meetingsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_callsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_frnt_fornitori_aziendaMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_aos_quotesMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_sr_servizi_richiestiMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_usersMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_leadsMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/dr_eventi_accountsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/DR_Eventi',
      'to' => 'modules/DR_Eventi',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'it_IT',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'it_IT',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/frnt_fornitori_azienda.php',
      'to_module' => 'frnt_fornitori_azienda',
      'language' => 'it_IT',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/frnt_fornitori_azienda.php',
      'to_module' => 'frnt_fornitori_azienda',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/AOS_Quotes.php',
      'to_module' => 'AOS_Quotes',
      'language' => 'it_IT',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/AOS_Quotes.php',
      'to_module' => 'AOS_Quotes',
      'language' => 'en_us',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sr_servizi_richiesti.php',
      'to_module' => 'sr_servizi_richiesti',
      'language' => 'it_IT',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sr_servizi_richiesti.php',
      'to_module' => 'sr_servizi_richiesti',
      'language' => 'en_us',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'it_IT',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'it_IT',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'it_IT',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/DR_Eventi.php',
      'to_module' => 'DR_Eventi',
      'language' => 'en_us',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'it_IT',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/it_IT.lang.php',
      'to_module' => 'application',
      'language' => 'it_IT',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_meetings_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_calls_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_frnt_fornitori_azienda_frnt_fornitori_azienda.php',
      'to_module' => 'frnt_fornitori_azienda',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_frnt_fornitori_azienda_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_aos_quotes_AOS_Quotes.php',
      'to_module' => 'AOS_Quotes',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_aos_quotes_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_sr_servizi_richiesti_sr_servizi_richiesti.php',
      'to_module' => 'sr_servizi_richiesti',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_sr_servizi_richiesti_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_users_Users.php',
      'to_module' => 'Users',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_users_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_leads_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_leads_Leads.php',
      'to_module' => 'Leads',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_accounts_DR_Eventi.php',
      'to_module' => 'DR_Eventi',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/dr_eventi_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'dr_eventi_meetings_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'dr_eventi_calls_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'frnt_fornitori_azienda' => 'dr_eventi_frnt_fornitori_azienda_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'AOS_Quotes' => 'dr_eventi_aos_quotes_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
        'sr_servizi_richiesti' => 'dr_eventi_sr_servizi_richiesti_name',
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'dr_eventi_users_name',
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);